#!/bin/bash
# Install the sidebar as an iTerm2 AutoLaunch script.
#
# Drops a stub into AutoLaunch/ that loads sidebar.py from this repo, rather
# than symlinking or copying. A copy goes stale the moment you edit the repo,
# and whether iTerm2 follows a symlink there was never established. The stub
# works either way, and editing sidebar.py needs no reinstall.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
autolaunch="$HOME/Library/Application Support/iTerm2/Scripts/AutoLaunch"
stub="$autolaunch/agents_sidebar.py"

if [ ! -d "$autolaunch" ]; then
  echo "error: $autolaunch does not exist." >&2
  echo "Open iTerm2 > Scripts > Manage > New Python Script once to create it." >&2
  exit 1
fi

# The shebang is what iTerm2 parses to choose an interpreter: it resolves
# iterm2env-3.10 from "python3.10". Both files carry it.
cat > "$stub" <<STUB
#!/usr/bin/env python3.10
"""Generated by install.sh. Loads the real script from the repo."""
import runpy

runpy.run_path("$repo/sidebar.py", run_name="__main__")
STUB

echo "installed stub -> $stub"
echo "        loading -> $repo/sidebar.py"

env="$HOME/Library/Application Support/iTerm2/iterm2env-3.10/versions/3.10.19/bin/python3"
if [ -x "$env" ]; then
  echo "runtime  -> $("$env" --version)"
else
  echo "warning: iterm2env-3.10 not found. iTerm2 will offer to download it." >&2
fi

echo
echo "Start it now without restarting iTerm2:"
echo "  Scripts > AutoLaunch > agents_sidebar"
echo "Then open the Toolbelt: View > Toolbelt > Agents (or Show Toolbelt, cmd-B)."

# The state hook ships as a Claude Code plugin, NOT as an edit to
# ~/.claude/settings.json. Eight council providers agreed there is no safe way
# for a third-party tool to co-edit that file: no hooks.d, no lock, no owner
# field, and other tools here (cs, herdr) rewrite it from templates. A plugin
# touches nothing shared, and uninstall is one command.
plugin_dir="$HOME/.claude/skills/agents-sidebar"
if [ -d "$repo/plugin" ]; then
  rm -rf "$plugin_dir"
  mkdir -p "$plugin_dir"
  # --exclude keeps __pycache__ out; the tests import the handler directly.
  (cd "$repo/plugin" && /usr/bin/tar cf - --exclude __pycache__ .) | (cd "$plugin_dir" && tar xf -)
  echo "installed plugin -> $plugin_dir"
  echo "        state hook loads next session, or run /reload-plugins now"
  echo "        uninstall:  claude plugin disable agents-sidebar@skills-dir"
fi

# The statusline bridge is opt-in, and deliberately not part of a plain
# install. It is the one piece that must edit ~/.claude/settings.json, which
# the note above rules out for everything else: cs rewrites that file from a
# template, so `cs -statusline enable` will silently displace the bridge and
# freeze the context figure. Reversible, and never done without asking.
#
# It buys the only context percentage that agrees with the one Claude Code
# draws. That payload is the sole place the context-window SIZE is published --
# the "[1m]" suffix is stripped from the model id before the request goes out,
# so 143k tokens is 14% of one window or 71% of another and the transcript
# cannot say which.
if [ "${1:-}" = "--statusline" ]; then
  settings="$HOME/.claude/settings.json"
  status_dir="$HOME/.claude/agents-sidebar-status"
  bridge="$repo/plugin/statusline-bridge.sh"

  command -v jq >/dev/null 2>&1 || { echo "error: --statusline needs jq." >&2; exit 1; }
  [ -f "$settings" ] || { echo "error: $settings not found." >&2; exit 1; }

  current=$(jq -r '.statusLine.command // ""' "$settings")
  mkdir -p "$status_dir"

  if [ "$current" = "$bridge" ]; then
    echo "statusline bridge already installed"
  else
    backup="$settings.before-agents-sidebar"
    cp "$settings" "$backup"
    # Saved before the swap, so the displaced statusline is recoverable even
    # if this script dies between here and the write below.
    printf '%s' "$current" > "$status_dir/original-statusline"
    tmp=$(mktemp)
    jq --arg cmd "$bridge" '.statusLine = {type: "command", command: $cmd, refreshInterval: 1}' \
      "$settings" > "$tmp" && mv "$tmp" "$settings"
    echo "statusline bridge -> $bridge"
    echo "        displaced -> ${current:-(none)}"
    echo "        saved to  -> $status_dir/original-statusline"
    echo "        backup    -> $backup"
  fi
  echo "        takes effect in sessions started from now on"
  echo "        undo:  cp \"$settings.before-agents-sidebar\" \"$settings\""
fi
