#!/bin/bash
# Install the sidebar as an iTerm2 AutoLaunch script.
#
# Drops a stub into AutoLaunch/ that loads sidebar.py from this repo, rather
# than symlinking or copying. A copy goes stale the moment you edit the repo,
# and whether iTerm2 follows a symlink there was never established. The stub
# works either way, and editing sidebar.py needs no reinstall.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
statusline=1; codex=auto
for arg in "$@"; do
  case "$arg" in
    --no-statusline) statusline=0 ;;
    --statusline) statusline=1 ;;
    --codex) codex=1 ;;
    --no-codex) codex=0 ;;
    *) echo "usage: ./install.sh [--no-statusline] [--codex | --no-codex]" >&2; exit 1 ;;
  esac
done
autolaunch="$HOME/Library/Application Support/iTerm2/Scripts/AutoLaunch"
stub="$autolaunch/agents_sidebar.py"

# One line per component, the details gathered under Next and Undo at the end.
# Colour only on a terminal: a log or a curl | bash transcript stays plain.
if [ -t 1 ]; then green=$'\e[32m'; yellow=$'\e[33m'; dim=$'\e[2m'; off=$'\e[0m'; else green=""; yellow=""; dim=""; off=""; fi
tilde() { printf '%s' "${1/#$HOME/~}"; }
line() { printf '  %s %s%-11s%s %s\n' "$1" "$dim" "$2" "$off" "$3"; }
ok()   { line "${green}✓${off}" "$1" "$2"; }
skip() { line "${dim}-${off}" "$1" "$2"; }
warn() { line "${yellow}!${off}" "$1" "$2" >&2; }
more() { printf '    %s%s%s\n' "$dim" "$1" "$off"; }
next=(); undo=()

printf '\n%sAgents sidebar%s %s\n\n' "$off" "$dim" "$(cat "$repo/VERSION" 2>/dev/null || echo "unreleased checkout")$off"

# iTerm2 makes this folder the first time you create a Python script; on a
# machine that never has, it reads what we put there just the same.
mkdir -p "$autolaunch"

# The shebang is what iTerm2 parses to choose an interpreter: it resolves
# iterm2env-3.10 from "python3.10". Both files carry it.
cat > "$stub" <<STUB
#!/usr/bin/env python3.10
"""Generated by install.sh. Loads the real script from the repo."""
import runpy

runpy.run_path("$repo/sidebar.py", run_name="__main__")
STUB

ok script "$(tilde "$stub")"
more "loads $(tilde "$repo")/sidebar.py"

# iTerm2 keeps its Python in a uv venv under ~/.config since 3.5.x, and in
# iterm2env under Application Support before that. Either serves python3.10.
runtime=""
for candidate in "$HOME/.config/iterm2/AppSupport/uv/venvs/3.10/bin/python" \
                 "$HOME/Library/Application Support/iTerm2/iterm2env-3.10/versions"/3.10.*/bin/python3; do
  if [ -x "$candidate" ]; then runtime="$candidate"; break; fi
done
if [ -n "$runtime" ]; then
  case "$runtime" in */uv/*) where="iTerm2's uv venv" ;; *) where="iterm2env" ;; esac
  ok runtime "$("$runtime" --version), $where"
else
  warn runtime "no iTerm2 Python 3.10 found; iTerm2 offers to download it when the script first runs"
fi
next+=("Start it:   Scripts > AutoLaunch > agents_sidebar"
       "Open it:    View > Toolbelt > Agents (cmd-B shows the Toolbelt)")

# The state hook ships as a Claude Code plugin, NOT as an edit to
# ~/.claude/settings.json. Eight council providers agreed there is no safe way
# for a third-party tool to co-edit that file: no hooks.d, no lock, no owner
# field, and other tools here (cs, herdr) rewrite it from templates. A plugin
# touches nothing shared, and uninstall is one command.
plugin_dir="$HOME/.claude/skills/agents-sidebar"
if [ -d "$repo/plugin" ]; then
  rm -rf "$plugin_dir"
  mkdir -p "$plugin_dir"
  # --exclude keeps __pycache__ out; the tests import the handler directly.
  (cd "$repo/plugin" && /usr/bin/tar cf - --exclude __pycache__ .) | (cd "$plugin_dir" && tar xf -)
  ok hook "$(tilde "$plugin_dir")"
  next+=("Hooks load in sessions started from now on; /reload-plugins for a running one.")
  undo+=("hook        claude plugin disable agents-sidebar@skills-dir")
fi

# The context figure on a card comes only from the statusline payload, so
# the bridge goes in by default; --no-statusline keeps settings.json untouched.
if [ "$statusline" = 1 ]; then
  settings="$HOME/.claude/settings.json"
  status_dir="$HOME/.claude/agents-sidebar-status"
  bridge="$repo/plugin/statusline-bridge.sh"
  # The panel's Install button runs the same step, so it lives in one place.
  result=$(python3 "$repo/statusline.py" "$settings" "$bridge" "$status_dir")
  if [ "$result" = already ]; then
    ok statusline "already installed"
  else
    displaced=$(printf '%s\n' "$result" | sed -n 2p)
    ok statusline "bridge set in $(tilde "$settings")"
    [ -n "$displaced" ] && more "your statusline, $displaced, runs inside it; kept in $(tilde "$status_dir")/original-statusline"
  fi
  undo+=("statusline  cp $(tilde "$settings").before-agents-sidebar $(tilde "$settings")   (or --no-statusline next time)")
else
  skip statusline "left alone (--no-statusline)"
fi

# Codex sessions as panel rows: on when Codex is here (its directory or its
# binary), so a machine without it sees nothing about it. --codex installs
# anyway, creating ~/.codex; --no-codex leaves Codex's files alone. Two files
# change: ~/.codex/hooks.json, which other tools write too (herdr registers
# its own entries there), so only our entries move; and config.toml, where
# Codex's sandbox learns the task directory. Codex asks once to trust the hooks.
if [ "$codex" = auto ]; then
  if [ -d "$HOME/.codex" ] || command -v codex >/dev/null 2>&1; then codex=1; else codex=0; fi
fi
if [ "$codex" = 1 ]; then
  codex_hooks="$HOME/.codex/hooks.json"
  mkdir -p "$HOME/.codex"
  # The first copy is the one worth keeping: a re-run must not replace the
  # file as it was before us with the file as we left it.
  [ -f "$codex_hooks" ] && [ ! -f "$codex_hooks.before-agents-sidebar" ] \
    && cp "$codex_hooks" "$codex_hooks.before-agents-sidebar"
  bash "$repo/codex-hooks.sh" "$codex_hooks" "$plugin_dir/hooks-handlers/emit-state.py"
  # Codex's sandbox writes only inside the workspace, so the task note the
  # agent keeps about its own work needs its directory opened up.
  tasks_dir="$HOME/.claude/agents-sidebar-tasks"
  mkdir -p "$tasks_dir"
  if python3 "$repo/codex-sandbox.py" "$HOME/.codex/config.toml" "$tasks_dir" 2>"$tasks_dir/.sandbox.err"; then
    ok codex "hooks and sandbox in ~/.codex"
  else
    ok codex "hooks in ~/.codex"
    warn codex "sandbox not opened, so the task line will not reach Codex cards: $(tr '\n' ' ' < "$tasks_dir/.sandbox.err")"
  fi
  rm -f "$tasks_dir/.sandbox.err"
  next+=("Codex asks once to trust its hooks.")
  [ -f "$codex_hooks.before-agents-sidebar" ] && undo+=("codex       cp $(tilde "$codex_hooks").before-agents-sidebar $(tilde "$codex_hooks")   (or --no-codex next time)")
else
  skip codex "not here"
fi

# The macOS notice for a finished turn or a question. A notification wears its
# SENDER's icon and name and nothing the poster passes changes that, and
# UNUserNotificationCenter refuses to run outside a bundle, so the panel posts
# through a small app of its own: assets/notifier.swift compiled by swiftc,
# our icon, our bundle id, an ad-hoc signature. Assembled in a staging
# directory and moved into place whole, so a failed build leaves the previous
# bundle standing. Rebuilt only when the source or the icon has changed:
# re-signing an unchanged bundle can make macOS ask for notification
# permission again, and this script runs after every plugin edit.
notifier_dest="$HOME/.local/share/agents-sidebar/Agents.app"
if ! command -v swiftc >/dev/null 2>&1; then
  warn notifier "off: swiftc not found; xcode-select --install, then ./install.sh again"
else
  icon="$repo/assets/notifier-icon.png"
  source="$repo/assets/notifier.swift"
  bundle_id="com.hexul.agents-sidebar.notifier"
  stamp="$(shasum -a 256 "$source" "$icon" | cut -d' ' -f1 | tr '\n' ' ')$bundle_id"
  if [ "$(cat "$notifier_dest/Contents/Resources/agents-sidebar-source.sha256" 2>/dev/null)" = "$stamp" ]; then
    ok notifier "$(tilde "$notifier_dest"), unchanged"
  else
    stage="$notifier_dest.staging.$$"; iconset="$notifier_dest.$$.iconset"
    rm -rf "$stage" "$iconset"
    mkdir -p "$stage/Contents/MacOS" "$stage/Contents/Resources" "$iconset"
    if ! swiftc -O -o "$stage/Contents/MacOS/agents-notifier" "$source" 2>"$stage.log"; then
      warn notifier "did not compile; keeping what is installed"
      sed 's/^/      /' "$stage.log" >&2
      rm -rf "$stage" "$stage.log" "$iconset"
    else
      rm -f "$stage.log"
      # The banner shows the icon at a few dozen points; 256 covers it at 2x
      # without shipping a megabyte of upscaled 1024s.
      for size in 16 32 64 128 256; do
        sips -z "$size" "$size" "$icon" --out "$iconset/icon_${size}x${size}.png" >/dev/null
      done
      cp "$iconset/icon_32x32.png" "$iconset/icon_16x16@2x.png"
      cp "$iconset/icon_64x64.png" "$iconset/icon_32x32@2x.png"
      cp "$iconset/icon_256x256.png" "$iconset/icon_128x128@2x.png"
      rm "$iconset/icon_64x64.png"
      iconutil -c icns "$iconset" -o "$stage/Contents/Resources/Agents.icns"
      rm -rf "$iconset"
      cat > "$stage/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>$bundle_id</string>
  <key>CFBundleName</key><string>Agents</string>
  <key>CFBundleDisplayName</key><string>Agents</string>
  <key>CFBundleExecutable</key><string>agents-notifier</string>
  <key>CFBundleIconFile</key><string>Agents</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST
      echo "$stamp" > "$stage/Contents/Resources/agents-sidebar-source.sha256"
      codesign --force -s - "$stage" 2>/dev/null
      # An executable that cannot run here still passes the -x test the
      # daemon makes, and every notice would then be lost silently.
      if "$stage/Contents/MacOS/agents-notifier" </dev/null >/dev/null 2>&1; [ $? -eq 2 ]; then
        rm -rf "$notifier_dest"
        mv "$stage" "$notifier_dest"
        /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$notifier_dest" >/dev/null 2>&1 || true
        ok notifier "$(tilde "$notifier_dest")"
        next+=("macOS asks once to allow notifications from Agents.")
      else
        rm -rf "$stage"
        warn notifier "the assembled bundle does not run here; keeping what is installed"
      fi
    fi
  fi
fi

printf '\nNext\n'
for item in "${next[@]}"; do printf '  %s\n' "$item"; done
if [ ${#undo[@]} -gt 0 ]; then
  printf '\nUndo\n'
  for item in "${undo[@]}"; do printf '  %s\n' "$item"; done
fi
