#!/bin/bash
# Install the sidebar as an iTerm2 AutoLaunch script.
#
# Drops a stub into AutoLaunch/ that loads sidebar.py from this repo, rather
# than symlinking or copying. A copy goes stale the moment you edit the repo,
# and whether iTerm2 follows a symlink there was never established. The stub
# works either way, and editing sidebar.py needs no reinstall.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
autolaunch="$HOME/Library/Application Support/iTerm2/Scripts/AutoLaunch"
stub="$autolaunch/agents_sidebar.py"

if [ ! -d "$autolaunch" ]; then
  echo "error: $autolaunch does not exist." >&2
  echo "Open iTerm2 > Scripts > Manage > New Python Script once to create it." >&2
  exit 1
fi

# The shebang is what iTerm2 parses to choose an interpreter: it resolves
# iterm2env-3.10 from "python3.10". Both files carry it.
cat > "$stub" <<STUB
#!/usr/bin/env python3.10
"""Generated by install.sh. Loads the real script from the repo."""
import runpy

runpy.run_path("$repo/sidebar.py", run_name="__main__")
STUB

echo "installed stub -> $stub"
echo "        loading -> $repo/sidebar.py"
echo "        release -> $(cat "$repo/VERSION" 2>/dev/null || echo "none, unreleased checkout")"

env="$HOME/Library/Application Support/iTerm2/iterm2env-3.10/versions/3.10.19/bin/python3"
if [ -x "$env" ]; then
  echo "runtime  -> $("$env" --version)"
else
  echo "warning: iterm2env-3.10 not found. iTerm2 will offer to download it." >&2
fi

echo
echo "Start it now without restarting iTerm2:"
echo "  Scripts > AutoLaunch > agents_sidebar"
echo "Then open the Toolbelt: View > Toolbelt > Agents (or Show Toolbelt, cmd-B)."

# The state hook ships as a Claude Code plugin, NOT as an edit to
# ~/.claude/settings.json. Eight council providers agreed there is no safe way
# for a third-party tool to co-edit that file: no hooks.d, no lock, no owner
# field, and other tools here (cs, herdr) rewrite it from templates. A plugin
# touches nothing shared, and uninstall is one command.
plugin_dir="$HOME/.claude/skills/agents-sidebar"
if [ -d "$repo/plugin" ]; then
  rm -rf "$plugin_dir"
  mkdir -p "$plugin_dir"
  # --exclude keeps __pycache__ out; the tests import the handler directly.
  (cd "$repo/plugin" && /usr/bin/tar cf - --exclude __pycache__ .) | (cd "$plugin_dir" && tar xf -)
  echo "installed plugin -> $plugin_dir"
  echo "        state hook loads next session, or run /reload-plugins now"
  echo "        uninstall:  claude plugin disable agents-sidebar@skills-dir"
fi

# The statusline bridge is opt-in, and deliberately not part of a plain
# install. It is the one piece that must edit ~/.claude/settings.json, which
# the note above rules out for everything else: cs rewrites that file from a
# template, so `cs -statusline enable` will silently displace the bridge and
# freeze the context figure. Reversible, and never done without asking.
#
# It buys the only context percentage that agrees with the one Claude Code
# draws. That payload is the sole place the context-window SIZE is published --
# the "[1m]" suffix is stripped from the model id before the request goes out,
# so 143k tokens is 14% of one window or 71% of another and the transcript
# cannot say which.
if [ "${1:-}" = "--statusline" ]; then
  settings="$HOME/.claude/settings.json"
  status_dir="$HOME/.claude/agents-sidebar-status"
  bridge="$repo/plugin/statusline-bridge.sh"

  command -v jq >/dev/null 2>&1 || { echo "error: --statusline needs jq." >&2; exit 1; }
  [ -f "$settings" ] || { echo "error: $settings not found." >&2; exit 1; }

  current=$(jq -r '.statusLine.command // ""' "$settings")
  mkdir -p "$status_dir"

  if [ "$current" = "$bridge" ]; then
    echo "statusline bridge already installed"
  else
    backup="$settings.before-agents-sidebar"
    cp "$settings" "$backup"
    # Saved before the swap, so the displaced statusline is recoverable even
    # if this script dies between here and the write below.
    printf '%s' "$current" > "$status_dir/original-statusline"
    tmp=$(mktemp)
    jq --arg cmd "$bridge" '.statusLine = {type: "command", command: $cmd, refreshInterval: 1}' \
      "$settings" > "$tmp" && mv "$tmp" "$settings"
    echo "statusline bridge -> $bridge"
    echo "        displaced -> ${current:-(none)}"
    echo "        saved to  -> $status_dir/original-statusline"
    echo "        backup    -> $backup"
  fi
  echo "        takes effect in sessions started from now on"
  echo "        undo:  cp \"$settings.before-agents-sidebar\" \"$settings\""
fi

# Codex sessions as panel rows are opt-in, for the same reason as the bridge:
# ~/.codex/hooks.json is shared (herdr registers its own entries there), so it
# is edited only when asked. The hooks run the installed copy of the handler.
if [ "${1:-}" = "--codex" ]; then
  codex_hooks="$HOME/.codex/hooks.json"
  [ -d "$HOME/.codex" ] || { echo "error: ~/.codex not found; is Codex installed?" >&2; exit 1; }
  [ -f "$codex_hooks" ] && cp "$codex_hooks" "$codex_hooks.before-agents-sidebar"
  bash "$repo/codex-hooks.sh" "$codex_hooks" "$plugin_dir/hooks-handlers/emit-state.py"
  echo "codex hooks -> $codex_hooks"
  # Codex's sandbox writes only inside the workspace, so the task note the
  # agent keeps about its own work needs its directory opened up. Appended
  # once; a config that already names the directory is left alone.
  codex_config="$HOME/.codex/config.toml"
  tasks_dir="$HOME/.claude/agents-sidebar-tasks"
  mkdir -p "$tasks_dir"
  if ! grep -qs "agents-sidebar-tasks" "$codex_config"; then
    printf '\n[sandbox_workspace_write]\nwritable_roots = ["%s"]\n' "$tasks_dir" >> "$codex_config"
    echo "codex sandbox -> $tasks_dir writable (config.toml [sandbox_workspace_write])"
  fi
  echo "        Codex asks once to trust them; takes effect in sessions started from now on"
  [ -f "$codex_hooks.before-agents-sidebar" ] && echo "        undo:  cp \"$codex_hooks.before-agents-sidebar\" \"$codex_hooks\""
fi

# The macOS notice for a finished turn or a question. A notification wears its
# SENDER's icon and name and nothing the poster passes changes that, and
# UNUserNotificationCenter refuses to run outside a bundle, so the panel posts
# through a small app of its own: assets/notifier.swift compiled by swiftc,
# our icon, our bundle id, an ad-hoc signature. Assembled in a staging
# directory and moved into place whole, so a failed build leaves the previous
# bundle standing. Rebuilt only when the source or the icon has changed:
# re-signing an unchanged bundle can make macOS ask for notification
# permission again, and this script runs after every plugin edit.
notifier_dest="$HOME/.local/share/agents-sidebar/Agents.app"
if ! command -v swiftc >/dev/null 2>&1; then
  echo "notifications off: swiftc not found (xcode-select --install), then re-run ./install.sh"
else
  icon="$repo/assets/notifier-icon.png"
  source="$repo/assets/notifier.swift"
  bundle_id="com.hexul.agents-sidebar.notifier"
  stamp="$(shasum -a 256 "$source" "$icon" | cut -d' ' -f1 | tr '\n' ' ')$bundle_id"
  if [ "$(cat "$notifier_dest/Contents/Resources/agents-sidebar-source.sha256" 2>/dev/null)" = "$stamp" ]; then
    echo "notifier bundle -> $notifier_dest (unchanged)"
  else
    stage="$notifier_dest.staging.$$"; iconset="$notifier_dest.$$.iconset"
    rm -rf "$stage" "$iconset"
    mkdir -p "$stage/Contents/MacOS" "$stage/Contents/Resources" "$iconset"
    if ! swiftc -O -o "$stage/Contents/MacOS/agents-notifier" "$source" 2>"$stage.log"; then
      echo "warning: the notifier did not compile; keeping what is installed" >&2
      sed 's/^/        /' "$stage.log" >&2
      rm -rf "$stage" "$stage.log" "$iconset"
    else
      rm -f "$stage.log"
      # The banner shows the icon at a few dozen points; 256 covers it at 2x
      # without shipping a megabyte of upscaled 1024s.
      for size in 16 32 64 128 256; do
        sips -z "$size" "$size" "$icon" --out "$iconset/icon_${size}x${size}.png" >/dev/null
      done
      cp "$iconset/icon_32x32.png" "$iconset/icon_16x16@2x.png"
      cp "$iconset/icon_64x64.png" "$iconset/icon_32x32@2x.png"
      cp "$iconset/icon_256x256.png" "$iconset/icon_128x128@2x.png"
      rm "$iconset/icon_64x64.png"
      iconutil -c icns "$iconset" -o "$stage/Contents/Resources/Agents.icns"
      rm -rf "$iconset"
      cat > "$stage/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>$bundle_id</string>
  <key>CFBundleName</key><string>Agents</string>
  <key>CFBundleDisplayName</key><string>Agents</string>
  <key>CFBundleExecutable</key><string>agents-notifier</string>
  <key>CFBundleIconFile</key><string>Agents</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST
      echo "$stamp" > "$stage/Contents/Resources/agents-sidebar-source.sha256"
      codesign --force -s - "$stage" 2>/dev/null
      # An executable that cannot run here still passes the -x test the
      # daemon makes, and every notice would then be lost silently.
      if "$stage/Contents/MacOS/agents-notifier" </dev/null >/dev/null 2>&1; [ $? -eq 2 ]; then
        rm -rf "$notifier_dest"
        mv "$stage" "$notifier_dest"
        /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$notifier_dest" >/dev/null 2>&1 || true
        echo "notifier bundle -> $notifier_dest"
        echo "        macOS asks once to allow notifications from Agents"
      else
        rm -rf "$stage"
        echo "warning: the assembled notifier does not run here; keeping what is installed" >&2
      fi
    fi
  fi
fi
